Fridge functionality
rafak1/GitFood-server pull request #3
Opened 2024-04-04 18:20 UTC by rafak1

Please review my changes :) 👍

2024-04-04 19:02 UTC, prolik123 requested changes
Niestety potrzebne są drobne zmiany

2024-04-04 19:02 UTC, prolik123 commented on Controllers/FridgeController.cs
> +    [HttpPost]
HttpDelete

2024-04-04 19:02 UTC, prolik123 commented on Controllers/FridgeController.cs
> +
Przydał by się jeszcze jakiś update rzeczy które masz w lodówce

2024-04-04 19:02 UTC, prolik123 commented on Controllers/FridgeController.cs
> +        await _dbInfo.Fridges.Where(x => x.Id == fridgeProductId).ExecuteDeleteAsync();
Wydaje mi się, wykonamy drugiego delete to tego pierwszego nie trzeba i on sam się zapnie ale do sprawdzenia dla pewnosci

2024-04-04 19:02 UTC, prolik123 commented on ViewModels/FridgeProductViewModel.cs
> +    public string Login { get; set; }
Niespójne entery

2024-04-04 19:02 UTC, prolik123 commented on DataModel/GitfoodContext.cs
> +     private readonly IConfiguration _configuration;
niepotrzeba spacja

2024-04-05 13:26 UTC, rafak1 commented on Controllers/FridgeController.cs
> +        await _dbInfo.Fridges.Where(x => x.Id == fridgeProductId).ExecuteDeleteAsync();
Nie działa bez tego pierwszego

2024-04-05 18:10 UTC, prolik123 approved these changes
Dobra robota 😀

2024-04-07 14:21 UTC, merged