Refactor + project separation + architectures changes
rafak1/GitFood-server pull request #6
Opened 2024-04-18 17:37 UTC by prolik123

2024-04-19 12:22 UTC, rafak1 requested changes
Ta struktura głównie mi się nie podoba

2024-04-19 12:22 UTC, rafak1 commented on Server.Controllers.Tests/ManagerActionResultMapperTest.cs
Nie lepiej jak Server Controllers i Tests to będą folder?

2024-04-19 12:22 UTC, rafak1 commented on Server.Controllers.Tests/ManagerActionResultMapperTest.cs
I czy testy nie powinny być całkowicie oddzielnie?
min. Tests/Server/Controllers/[...]Test.cs

2024-04-19 12:22 UTC, rafak1 commented on Server.Controllers/ResultEnumToStatusCodeMapper.cs
> +                _ => throw new InvalidOperationException("Unexpected Http status to map")
Trochę ograniczające, zamiast exception można by zwracać 501

2024-04-19 12:22 UTC, rafak1 commented on Server.Controllers/ManagerResultMapper.cs
> +        object data;
W jednej lini?

2024-04-19 12:22 UTC, rafak1 commented on Server.Data/Models/Barcode.cs
Dalej te foldery mi się nie podobają, zwłaszcza że tu są pomieszane

2024-04-19 12:22 UTC, rafak1 commented on Server.Logic.Tests/UnitTest1.cs
To samo, foldery, i struktura testów

2024-04-19 13:38 UTC, prolik123 commented on Server.Controllers.Tests/ManagerActionResultMapperTest.cs
Są właśnie jako odzielny projekt w solucji

2024-04-19 13:39 UTC, prolik123 commented on Server.Controllers.Tests/ManagerActionResultMapperTest.cs
To jest po to żeby nie pchać NUnita do zależności innego projektu temu się tworzy osobny projekt do testów

2024-04-19 13:40 UTC, prolik123 commented on Server.Controllers/ResultEnumToStatusCodeMapper.cs
> +                _ => throw new InvalidOperationException("Unexpected Http status to map")
Jeżeli wyleci exception to automatycznie leci 500 Internal Server Error

2024-04-20 10:56 UTC, prolik123 commented on Server.Controllers/ManagerResultMapper.cs
> +        object data;
fixed

2024-04-20 11:09 UTC, merged